print(complex(3))
print(complex(50+2j))
print(complex(False))
print(complex(True))
print(complex("4.22"))
print(complex("4"))
print(complex(4.22))
# print((complex("name")))
# print(complex(" "))
print(complex(3, -5))